# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20161011_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(upload_to=b''),
        ),
    ]
