# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20161014_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(upload_to='signup/static/media'),
        ),
    ]
